server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false

logging:
  level:
    root: ${LOG_ROOT_LEVEL:INFO}
    com.planix.backend: ${LOG_APP_LEVEL:DEBUG}
    org.springframework.web: ${LOG_WEB_LEVEL:INFO}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}